# Generated by Django 2.1.4 on 2019-02-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='payment_reference_number',
            field=models.CharField(default='asdasd', help_text='If paid in cash, just write CASH', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
