# Generated by Django 2.1.4 on 2018-12-20 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('college_name',),
            },
        ),
        migrations.AlterModelOptions(
            name='college',
            options={},
        ),
        migrations.RemoveField(
            model_name='college',
            name='user',
        ),
        migrations.AlterField(
            model_name='students',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserCollege'),
        ),
        migrations.AddField(
            model_name='usercollege',
            name='college_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.College'),
        ),
        migrations.AddField(
            model_name='usercollege',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
