# Generated by Django 2.1.4 on 2019-02-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_shirt_payment_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='payment_reference_number',
            field=models.CharField(help_text='If paid in cash, just write CASH', max_length=100),
        ),
    ]
