# Generated by Django 2.1.4 on 2018-12-20 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181220_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ('college_name',)},
        ),
        migrations.AlterField(
            model_name='students',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserCollege'),
        ),
        migrations.AlterField(
            model_name='students',
            name='participant_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
