# Generated by Django 2.1.4 on 2018-12-28 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
