# Generated by Django 2.1.4 on 2019-02-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190208_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='TShirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('shirt_size', models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=5)),
                ('payment_reference_number', models.CharField(help_text='If paid in cash, just write CASH', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Shirt',
        ),
    ]
