# Generated by Django 2.1.4 on 2018-12-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181220_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=100)),
                ('shirt_size', models.CharField(max_length=5)),
            ],
        ),
    ]
