# Generated by Django 2.1.4 on 2018-12-28 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=10)),
                ('topic', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='photography_pics')),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.College')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
