# Generated by Django 2.1.4 on 2018-12-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_shirt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='roll_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
