# Generated by Django 2.1.4 on 2018-12-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181221_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='shirt_size',
            field=models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=5),
        ),
    ]
