# Generated by Django 2.1.4 on 2018-12-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181229_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='desc',
            new_name='description',
        ),
    ]
