# Generated by Django 2.1.4 on 2018-12-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20181229_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoregistration',
            name='college',
        ),
        migrations.RemoveField(
            model_name='userphoto',
            name='photo_reg',
        ),
        migrations.DeleteModel(
            name='PhotoRegistration',
        ),
        migrations.DeleteModel(
            name='UserPhoto',
        ),
    ]
