# Generated by Django 2.1.4 on 2018-12-31 04:21

import django.core.validators
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='image',
            field=models.ImageField(upload_to='photography_pics', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), events.models.UserPhoto.validate_image]),
        ),
    ]
