# Generated by Django 2.1.4 on 2018-12-30 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181230_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoregistration',
            name='college',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.College'),
        ),
    ]
