# Generated by Django 2.1.4 on 2018-12-31 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181231_0125'),
        ('events', '0002_auto_20181231_0421'),
    ]

    operations = [
    ]
