# Generated by Django 2.1.4 on 2019-02-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_carddetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetail',
            name='college_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
